/** @type {import('next').NextConfig} */
// NOTE: the sitemap is generated by the `prebuild` npm script, not from a
// bundler hook - the build uses Turbopack, which never calls webpack().
module.exports = {
  turbopack: {},
};
